# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'LBTA-18-twitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBTA-18-twitter
pod 'LBTAComponents', '~> 0.1.9'

end
