# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'LBTA-12-google-login-sdk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google/SignIn'

  # Pods for LBTA-12-google-login-sdk

end
